### ISSUE TITLE
Page Overflow

### ISSUE THREAD

**Issue by abhrajit2004** [5h0ov/Immersive-WebCamp-Project-1#1]

**Comment by 5h0ov** [comment]
gib the pic of the mentioned portion broo

**Comment by abhrajit2004** [comment]
![image](https://github.com/5h0ov/Immersive-WebCamp-Project-1/assets/116187246/ca5402b0-f2c0-4c10-851b-924e9ef5a1a4)

**Comment by abhrajit2004** [comment]
there's a horizontal scroll bar

**Comment by 5h0ov** [comment]
@abhrajit2004  ok u can fix it 😊💀

**Comment by abhrajit2004** [comment]
Ok Mate!
